/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Sales } from "./Sales";
import { SalesCountArgs } from "./SalesCountArgs";
import { SalesFindManyArgs } from "./SalesFindManyArgs";
import { SalesFindUniqueArgs } from "./SalesFindUniqueArgs";
import { CreateSalesArgs } from "./CreateSalesArgs";
import { UpdateSalesArgs } from "./UpdateSalesArgs";
import { DeleteSalesArgs } from "./DeleteSalesArgs";
import { SalesService } from "../sales.service";
@graphql.Resolver(() => Sales)
export class SalesResolverBase {
  constructor(protected readonly service: SalesService) {}

  async _salesItemsMeta(
    @graphql.Args() args: SalesCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Sales])
  async salesItems(@graphql.Args() args: SalesFindManyArgs): Promise<Sales[]> {
    return this.service.salesItems(args);
  }

  @graphql.Query(() => Sales, { nullable: true })
  async sales(
    @graphql.Args() args: SalesFindUniqueArgs
  ): Promise<Sales | null> {
    const result = await this.service.sales(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Sales)
  async createSales(@graphql.Args() args: CreateSalesArgs): Promise<Sales> {
    return await this.service.createSales({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Sales)
  async updateSales(
    @graphql.Args() args: UpdateSalesArgs
  ): Promise<Sales | null> {
    try {
      return await this.service.updateSales({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Sales)
  async deleteSales(
    @graphql.Args() args: DeleteSalesArgs
  ): Promise<Sales | null> {
    try {
      return await this.service.deleteSales(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
