/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  ProductionPerDay as PrismaProductionPerDay,
} from "@prisma/client";

export class ProductionPerDayServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.ProductionPerDayCountArgs, "select">
  ): Promise<number> {
    return this.prisma.productionPerDay.count(args);
  }

  async productionPerDays<T extends Prisma.ProductionPerDayFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.ProductionPerDayFindManyArgs>
  ): Promise<PrismaProductionPerDay[]> {
    return this.prisma.productionPerDay.findMany<Prisma.ProductionPerDayFindManyArgs>(
      args
    );
  }
  async productionPerDay<T extends Prisma.ProductionPerDayFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.ProductionPerDayFindUniqueArgs>
  ): Promise<PrismaProductionPerDay | null> {
    return this.prisma.productionPerDay.findUnique(args);
  }
  async createProductionPerDay<T extends Prisma.ProductionPerDayCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.ProductionPerDayCreateArgs>
  ): Promise<PrismaProductionPerDay> {
    return this.prisma.productionPerDay.create<T>(args);
  }
  async updateProductionPerDay<T extends Prisma.ProductionPerDayUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.ProductionPerDayUpdateArgs>
  ): Promise<PrismaProductionPerDay> {
    return this.prisma.productionPerDay.update<T>(args);
  }
  async deleteProductionPerDay<T extends Prisma.ProductionPerDayDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.ProductionPerDayDeleteArgs>
  ): Promise<PrismaProductionPerDay> {
    return this.prisma.productionPerDay.delete(args);
  }
}
