/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Expenses as PrismaExpenses } from "@prisma/client";

export class ExpensesServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.ExpensesCountArgs, "select">): Promise<number> {
    return this.prisma.expenses.count(args);
  }

  async expensesItems<T extends Prisma.ExpensesFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.ExpensesFindManyArgs>
  ): Promise<PrismaExpenses[]> {
    return this.prisma.expenses.findMany<Prisma.ExpensesFindManyArgs>(args);
  }
  async expenses<T extends Prisma.ExpensesFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.ExpensesFindUniqueArgs>
  ): Promise<PrismaExpenses | null> {
    return this.prisma.expenses.findUnique(args);
  }
  async createExpenses<T extends Prisma.ExpensesCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.ExpensesCreateArgs>
  ): Promise<PrismaExpenses> {
    return this.prisma.expenses.create<T>(args);
  }
  async updateExpenses<T extends Prisma.ExpensesUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.ExpensesUpdateArgs>
  ): Promise<PrismaExpenses> {
    return this.prisma.expenses.update<T>(args);
  }
  async deleteExpenses<T extends Prisma.ExpensesDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.ExpensesDeleteArgs>
  ): Promise<PrismaExpenses> {
    return this.prisma.expenses.delete(args);
  }
}
